# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oUjITBDPki7jZWTDHqKi44eE9Q2xaRrz
"""

from collaborativeFiltering import filteringRecommender

def runRecommendation(choice):
    if (choice == 2):
        print("Enter your userId: ", end=' ')
        userId = int(input())
        filteringRecommender(userId)

if __name__ == "__main__":
    print("How would you like to generate movies?")
    print("     1. Find similar movies to your favorite")
    print("     2. Movies tailored to you")
    print("     3. Hybrid approach")
    print("Enter your choice: ", end=' ')
    choice = int(input())
    runRecommendation(choice)
    print()